This is makeindex, version 2.15 [MiKTeX 2.9.7140 64-bit] (kpathsea + Thai support).
Scanning style file ./softengCoursework.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file softengCoursework.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (63 comparisons).
Generating output file softengCoursework.acr....done (17 lines written, 0 warnings).
Output written in softengCoursework.acr.
Transcript written in softengCoursework.alg.
